name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v1.0.1, etc.

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew clean build jar
      
      - name: Get tag name
        id: tag_name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.tag_name.outputs.TAG }}
          draft: false
          prerelease: false
          body: |
            ## SSE Viewer Release ${{ steps.tag_name.outputs.TAG }}
            
            ### Installation
            1. Download `sse-viewer.jar` from the assets below
            2. Load the extension in Burp Suite via Extensions > Add
            
            ### Changes
            See commit history for details.
      
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/sse-viewer.jar
          asset_name: sse-viewer.jar
          asset_content_type: application/java-archive

